# Generated by Django 3.2.8 on 2021-10-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.interval'),
        ),
    ]
